import * as THREE from 'three';
import {Settings} from './Settings.js';
import {Input} from './Input.js';
import {GameAudio} from './Audio.js';
import {World} from '../world/World.js';
import {B,BLOCKS} from '../world/Blocks.js';
import {Renderer} from '../render/Renderer.js';
import {TextureAtlas} from '../render/TextureAtlas.js';
import {Sky} from '../render/Sky.js';
import {Particles} from '../render/Particles.js';
import {Player} from '../player/Player.js';
import {canStand,overlapsPlayer} from '../player/Physics.js';
import {raycast} from '../player/Raycast.js';
import {HUD} from '../ui/HUD.js';
import {Inventory} from '../ui/Inventory.js';
import {Menus} from '../ui/Menus.js';
/** Coordinates independent game systems and the fixed-step/render loop. */
export class Engine{
 /** @param {import('../save/SaveManager.js').SaveManager} saveManager @param {object|null} saved */
 constructor(saveManager,saved){this.saves=saveManager;this.settings=new Settings();this.renderer=new Renderer(document.getElementById('scene'));this.atlas=new TextureAtlas();this.world=new World(this.renderer.scene,this.atlas.materials,saved?.seed||'wildwood',saved?.diffs||{});this.sky=new Sky(this.renderer.scene);this.sky.time=saved?.progress?.time??100;this.player=new Player(saved?.player);this.hud=new HUD();this.hud.restore(saved?.progress);this.inventory=new Inventory(saved?.inventory);this.inventory.creative=this.player.creative;this.input=new Input(this.renderer.gl.domElement,this.settings);this.audio=new GameAudio(this.settings);this.particles=new Particles(this.renderer.scene);this.menus=new Menus(this);this.started=false;this.ready=false;this.accumulator=0;this.lastTime=performance.now();this.elapsed=0;this.mineTime=0;this.mineKey='';this.autoMine=false;this.placeCooldown=0;this.stepTime=0;this.direction=new THREE.Vector3();this.hit=null;this.savedSpawn=!!saved;this.hasAdventure=!!saved;this.lastSave=0;this.saveTimeout=0;this.lastWorldError='';this.lastUnlock=-Infinity;this.deathShown=false;this.modeChoice=this.player.creative?'creative':'survival';this.spawn=[this.player.position.x,this.player.position.y,this.player.position.z];
 this.input.onLook=(dx,dy)=>{if(this.started&&!this.menus.opened)this.player.look(dx,dy);};this.input.onAction=code=>this.action(code);this.input.onScroll=delta=>this.inventory.select(this.inventory.selected+delta);this.input.onLock=locked=>{if(!locked)this.lastUnlock=performance.now();if(!locked&&this.started&&!this.menus.opened&&!this.player.dead)this.menus.show('pause');if(locked&&this.started)document.getElementById('crosshair').hidden=false;};this.player.onDamage=()=>{this.hud.damage();this.audio.play('break');};this.inventory.toast=message=>this.hud.toast(message);this.inventory.onChange=()=>{if(this.started)this.queueSave();};this.inventory.onCraft=()=>{this.hud.crafted++;this.audio.play('craft');};this.inventory.nearBench=()=>{const p=this.player.position;for(let y=-2;y<=2;y++)for(let z=-3;z<=3;z++)for(let x=-3;x<=3;x++)if(this.world.getBlock(Math.floor(p.x)+x,Math.floor(p.y)+y,Math.floor(p.z)+z)===B.WORKBENCH)return true;return false;};this.world.onEdit=()=>this.queueSave();this.saves.onStatus=status=>document.getElementById('save-status').textContent=status;
 document.getElementById('enter-world').onclick=()=>this.enter();document.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>{this.modeChoice=button.dataset.mode;this.setCreative(this.modeChoice==='creative');this.updateWelcome();});document.getElementById('sound-toggle').onclick=()=>{this.audio.start();document.getElementById('sound-toggle').setAttribute('aria-pressed',String(this.audio.toggle()));};document.getElementById('sound-toggle').setAttribute('aria-pressed',String(this.settings.sound));this.renderer.gl.domElement.addEventListener('click',()=>{if(this.started&&!this.menus.opened&&!this.input.active)this.input.lock();});
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&this.started){this.save();this.input.clear();if(!this.menus.opened)this.menus.show('pause');}});window.addEventListener('pagehide',()=>{if(this.hasAdventure)this.save();});this.renderer.gl.domElement.addEventListener('webglcontextlost',event=>{event.preventDefault();this.menus.show('pause');this.hud.toast('Graphics paused. Reload to restore your saved world.');});this.updateWelcome();this.inventory.render();this.frame=this.frame.bind(this);requestAnimationFrame(this.frame);}
 /** Update mode and returning-player text in the opening panel. */
 updateWelcome(){document.querySelectorAll('[data-mode]').forEach(button=>button.classList.toggle('selected',(button.dataset.mode==='creative')===this.player.creative));document.getElementById('mode-description').textContent=this.player.creative?'An open sky. Unlimited blocks. Build freely.':'Gather, craft, and find your footing.';document.getElementById('world-seed-label').textContent=`WORLD / ${this.world.seed.toUpperCase()}`;if(this.hasAdventure){document.getElementById('welcome-save-note').textContent='Your little world is waiting for you';if(this.ready)document.getElementById('enter-label').textContent='Back to your world';}else if(this.ready)document.getElementById('enter-label').textContent='Enter the world';}
 /** Activate the current world from the start button's user gesture. */
 enter(){if(!this.ready)return;this.started=true;this.hasAdventure=true;this.accumulator=0;this.player.previous.copy(this.player.position);this.audio.start();this.setCreative(this.player.creative);document.body.classList.add('playing');document.getElementById('welcome').hidden=true;document.getElementById('vista-note').hidden=true;document.getElementById('crosshair').hidden=false;this.menus.opened=null;this.menus.layer.hidden=true;this.input.lock();if(this.player.dead||this.player.health<=0){this.player.dead=true;this.showDeath();}else this.hud.toast(this.player.creative?'Your world, your rules. Press F to fly.':'Welcome to the woods. Take your time.');this.save();}
 /** Keep the live world visible behind the home panel. */
 home(){this.started=false;this.input.unlock();document.body.classList.remove('playing');document.getElementById('welcome').hidden=false;document.getElementById('vista-note').hidden=false;document.getElementById('crosshair').hidden=true;document.getElementById('journey-card').hidden=true;this.renderer.select(null);this.hud.target(null,0);this.updateWelcome();}
 /** Toggle free building and damage immunity. */
 setCreative(enabled){this.player.creative=enabled;if(!enabled)this.player.flying=false;this.inventory.creative=enabled;this.inventory.render();this.modeChoice=enabled?'creative':'survival';document.getElementById('mode-status').textContent=enabled?'CREATIVE':'SURVIVAL';this.updateWelcome();if(this.started)this.queueSave();}
 /** Dispatch non-continuous controls. */
 action(code){if(code==='F3'){this.hud.debug=!this.hud.debug;return;}if(code==='Escape'){if(performance.now()-this.lastUnlock<200)return;if(this.menus.opened){if(this.menus.opened!=='death')this.menus.close(this.started);}else if(this.started)this.menus.show('pause');return;}if(code==='KeyE'){if(!this.started){this.menus.show('inventory');return;}if(this.menus.opened==='inventory')this.menus.close(true);else if(!this.menus.opened)this.menus.show('inventory');return;}if(!this.started||this.menus.opened||this.player.dead)return;if(/^Digit[1-9]$/.test(code))this.inventory.select(Number(code.at(-1))-1);if(code==='KeyF'){if(this.player.creative){this.player.flying=!this.player.flying;this.player.velocity.y=0;this.hud.toast(this.player.flying?'Taking the scenic route. Space rises, Ctrl descends.':'Feet on the ground.');}else this.hud.toast('Flight is available in creative mode. Change modes in settings.');}if(code==='KeyQ'&&this.inventory.current){const{id}=this.inventory.current;this.renderer.camera.getWorldDirection(this.direction);const p=this.player.position;this.particles.drop(p.x+this.direction.x*.8,p.y+1.2,p.z+this.direction.z*.8,id,1);this.inventory.consume();this.audio.play('place');}}
 /** Find and validate a safe loaded spawn before enabling play. */
 checkReady(){let completed=0;const cx=Math.floor(this.player.position.x/16),cz=Math.floor(this.player.position.z/16);for(let dz=-1;dz<=1;dz++)for(let dx=-1;dx<=1;dx++)if(this.world.chunks.get(`${cx+dx},${cz+dz}`)?.blocks)completed++;document.querySelector('#loading-progress span').style.width=`${completed/9*100}%`;if(completed<9)return;let found=this.savedSpawn&&canStand(this.player.position,this.world);if(!found){const baseX=Math.floor(this.player.position.x),baseZ=Math.floor(this.player.position.z);for(let radius=0;radius<=12&&!found;radius++)for(let dz=-radius;dz<=radius&&!found;dz++)for(let dx=-radius;dx<=radius&&!found;dx++){const x=baseX+dx+.5,z=baseZ+dz+.5,y=this.world.surface(x,z);if(y!==null&&y>62){const point=new THREE.Vector3(x,y,z);if(canStand(point,this.world)){this.player.position.copy(point);found=true;}}}}
 if(!found)return;this.player.previous.copy(this.player.position);this.player.fallStart=this.player.position.y;this.spawn=this.player.position.toArray();this.ready=true;document.getElementById('enter-world').disabled=false;document.getElementById('loading-progress').hidden=true;this.updateWelcome();}
 /** Perform DDA targeting and timed mining / placement. */
 interact(dt){const{camera}=this.renderer;camera.getWorldDirection(this.direction);this.hit=raycast(this.world,camera.position,this.direction,5);this.placeCooldown=Math.max(0,this.placeCooldown-dt);if(this.input.tapBreak){this.autoMine=true;this.input.tapBreak=false;}const mining=this.input.left||this.autoMine,hit=this.hit;let progress=0;
 if(hit&&mining&&hit.id!==B.BEDROCK){const key=`${hit.x},${hit.y},${hit.z}`;if(this.mineKey!==key){this.mineKey=key;this.mineTime=0;}this.mineTime+=dt;const item=this.inventory.current,tool=BLOCKS[item?.id]?.tool||1,hardness=this.player.creative ? .001 : BLOCKS[hit.id].hardness/tool;progress=this.mineTime/(this.player.creative ? .001 : Math.max(.08,hardness));if(progress>=1){this.breakBlock(hit);this.mineTime=0;this.mineKey='';this.autoMine=false;progress=0;}}else{this.mineTime=0;this.mineKey='';if(!hit)this.autoMine=false;}
 if(this.input.right){this.input.right=false;if(this.placeCooldown===0){this.placeCooldown=.18;this.placeBlock(hit);}}if(this.input.pick){this.input.pick=false;if(hit)this.inventory.pick(hit.id);}this.renderer.select(hit,progress);this.hud.target(hit?{...hit,name:BLOCKS[hit.id].name}:null,progress);}
 /** Remove a block and grant its mined result or drop it when the satchel is full. */
 breakBlock(hit){if(!this.world.setBlock(hit.x,hit.y,hit.z,B.AIR))return;this.particles.burst(hit.x,hit.y,hit.z,hit.id);this.audio.play('break');this.hud.mined++;if(!this.player.creative){const drop=hit.id===B.STONE?B.COBBLE:hit.id===B.GRASS?B.DIRT:hit.id;if(!this.inventory.add(drop,1))this.particles.drop(hit.x+.5,hit.y+.5,hit.z+.5,drop);if(hit.id===B.LEAVES&&Math.random()<.27){if(!this.inventory.add(B.BERRY,1))this.particles.drop(hit.x+.5,hit.y+.5,hit.z+.5,B.BERRY);else this.hud.toast('A few wild berries. A little luck.');}}}
 /** Place the selected block after checking occupancy and player collision. */
 placeBlock(hit){const item=this.inventory.current;if(!item){this.hud.toast('Choose a block from your hotbar first.');return;}if(BLOCKS[item.id].food){if(this.player.hunger>=20&&this.player.health>=20){this.hud.toast('You’re feeling well fed. Save it for the road.');return;}this.player.hunger=Math.min(20,this.player.hunger+BLOCKS[item.id].food);this.player.health=Math.min(20,this.player.health+2);this.inventory.consume();this.audio.play('eat');return;}if(!BLOCKS[item.id].placeable){this.hud.toast('Hold left click to mine with your pickaxe.');return;}if(!hit)return;const[x,y,z]=[hit.x+hit.normal[0],hit.y+hit.normal[1],hit.z+hit.normal[2]];const previous=this.world.getBlock(x,y,z);if(previous!==B.AIR&&previous!==B.WATER)return;if(BLOCKS[item.id].solid&&overlapsPlayer(x,y,z,this.player.position,this.player.crouching?1.5:1.8)){this.hud.toast('Take a small step back to place that block.');return;}if(this.world.setBlock(x,y,z,item.id)){this.inventory.consume();this.hud.placed++;this.audio.play('place');}}
 /** Save once after a burst of edits, while retaining the 30-second autosave. */
 queueSave(){clearTimeout(this.saveTimeout);this.saveTimeout=setTimeout(()=>this.save(),400);}
 /** Persist only player state, inventory, milestones, and modified voxels. */
 save(){if(!this.hasAdventure)return;clearTimeout(this.saveTimeout);this.lastSave=this.elapsed;this.saves.save({seed:this.world.seed,player:this.player.serialize(),inventory:this.inventory.slots,progress:{...this.hud.serialize(),time:this.sky.time},diffs:this.world.diffs});}
 /** Open the death dialog exactly once. */
 showDeath(){if(this.deathShown)return;this.deathShown=true;this.menus.show('death');}
 /** Choose a safe local clearing and restore the player's meters. */
 respawn(){let chosen=null;const p=this.player.position;for(let r=0;r<16&&!chosen;r++)for(let z=-r;z<=r&&!chosen;z++)for(let x=-r;x<=r&&!chosen;x++){const wx=Math.floor(p.x)+x+.5,wz=Math.floor(p.z)+z+.5,y=this.world.surface(wx,wz);if(y!==null&&y>62){const point=new THREE.Vector3(wx,y,wz);if(canStand(point,this.world))chosen=point;}}if(!chosen){this.hud.toast('The clearing is still growing. Try again in a moment.');return;}this.player.respawn(chosen.x,chosen.y,chosen.z);this.deathShown=false;this.menus.opened=null;this.menus.close(true);this.save();}
 /** Render one animation frame with a bounded fixed-step accumulator. */
 frame(now){requestAnimationFrame(this.frame);const dt=Math.min(.1,Math.max(0,(now-this.lastTime)/1000));this.lastTime=now;this.elapsed+=dt;this.world.update(this.player.position.x,this.player.position.z,this.settings.distance);if(!this.ready)this.checkReady();const active=this.started&&this.input.active&&!this.menus.opened&&!this.player.dead;
 if(active){this.accumulator=Math.min(.1,this.accumulator+dt);while(this.accumulator>=1/60){this.player.update(1/60,this.input,this.world);this.accumulator-=1/60;}this.player.pose(this.renderer.camera,this.accumulator*60,dt,this.settings.fov);this.interact(dt);this.particles.update(dt,this.player,this.inventory,this.world);this.stepTime+=dt;if(this.stepTime>.42&&this.player.grounded&&Math.hypot(this.player.velocity.x,this.player.velocity.z)>1){this.audio.play('step');this.stepTime=0;}}else if(!this.started){const p=this.player.position;const baseY=this.ready?p.y:68;this.renderer.camera.position.set(p.x+35,baseY+19,p.z+33);this.renderer.camera.lookAt(p.x-28,baseY-5,p.z-64);this.renderer.camera.fov=58;this.renderer.camera.updateProjectionMatrix();}else this.accumulator=0;
 this.sky.update(active?dt:0,this.renderer.camera.position,this.settings.distance);this.hud.update(dt,this);this.renderer.draw();if(this.started&&this.player.dead)this.showDeath();if(this.started&&this.elapsed-this.lastSave>30)this.save();if(this.world.error&&this.lastWorldError!==this.world.error){this.lastWorldError=this.world.error;this.hud.toast(this.world.error);}}
}
