/** Keyboard, pointer lock, mouse buttons, and touch controls. */
export class Input{
 /** @param {HTMLCanvasElement} canvas @param {import('./Settings.js').Settings} settings */
 constructor(canvas,settings){this.canvas=canvas;this.settings=settings;this.keys=new Set();this.pressed=new Set();this.active=false;this.left=false;this.right=false;this.pick=false;this.tapBreak=false;this.moveX=0;this.moveZ=0;this.onLook=()=>{};this.onAction=()=>{};this.onLock=()=>{};this.onScroll=()=>{};this.touch=matchMedia('(pointer: coarse)').matches;
 document.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;if(['F3','Space','Tab','KeyE','KeyQ','KeyF','ControlLeft','ControlRight'].includes(e.code))e.preventDefault();if(!this.keys.has(e.code))this.pressed.add(e.code);this.keys.add(e.code);if(!e.repeat)this.onAction(e.code);});document.addEventListener('keyup',e=>this.keys.delete(e.code));window.addEventListener('blur',()=>this.clear());
 document.addEventListener('pointerlockchange',()=>{this.active=document.pointerLockElement===canvas;this.clear();this.onLock(this.active);});document.addEventListener('pointerlockerror',()=>{this.active=true;this.onLock(true);});document.addEventListener('mousemove',e=>{if(this.active&&(document.pointerLockElement===canvas||(!document.pointerLockElement&&e.target===canvas)))this.onLook(e.movementX*this.settings.sensitivity*.0025,e.movementY*this.settings.sensitivity*.0025);});
 canvas.addEventListener('mousedown',e=>{if(!this.active)return;e.preventDefault();if(e.button===0)this.left=true;if(e.button===2)this.right=true;if(e.button===1)this.pick=true;});document.addEventListener('mouseup',e=>{if(e.button===0)this.left=false;});canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('wheel',e=>{if(this.active){e.preventDefault();this.onScroll(Math.sign(e.deltaY));}},{passive:false});
 let lookPointer=null,lastX=0,lastY=0,moved=false,started=0,timer;canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'||!this.active)return;lookPointer=e.pointerId;lastX=e.clientX;lastY=e.clientY;started=performance.now();moved=false;canvas.setPointerCapture(e.pointerId);timer=setTimeout(()=>{if(!moved)this.right=true;},480);});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==lookPointer)return;const dx=e.clientX-lastX,dy=e.clientY-lastY;if(Math.abs(dx)+Math.abs(dy)>2){moved=true;clearTimeout(timer);}this.onLook(dx*.005,dy*.005);lastX=e.clientX;lastY=e.clientY;});const end=e=>{if(e.pointerId!==lookPointer)return;clearTimeout(timer);if(!moved&&performance.now()-started<480)this.tapBreak=true;lookPointer=null;};canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',e=>{clearTimeout(timer);if(e.pointerId===lookPointer)lookPointer=null;});
 const stick=document.getElementById('touch-stick'),knob=stick.querySelector('span');let stickPointer=null;const reset=()=>{stickPointer=null;this.moveX=this.moveZ=0;knob.style.transform='translate(0,0)';};stick.addEventListener('pointerdown',e=>{stickPointer=e.pointerId;stick.setPointerCapture(e.pointerId);});stick.addEventListener('pointermove',e=>{if(e.pointerId!==stickPointer)return;const r=stick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,len=Math.max(36,Math.hypot(dx,dy));this.moveX=dx/len;this.moveZ=dy/len;knob.style.transform=`translate(${this.moveX*30}px,${this.moveZ*30}px)`;});stick.addEventListener('pointerup',reset);stick.addEventListener('pointercancel',reset);document.getElementById('touch-jump').addEventListener('pointerdown',()=>{this.keys.add('Space');this.pressed.add('Space');});document.getElementById('touch-jump').addEventListener('pointerup',()=>this.keys.delete('Space'));document.getElementById('touch-inventory').addEventListener('click',()=>this.onAction('KeyE'));}
 /** Request first-person mouse capture directly from a user gesture. */
 lock(){if(this.touch){this.active=true;this.onLock(true);return;}try{const result=this.canvas.requestPointerLock();if(result?.catch)result.catch(()=>{this.active=true;this.onLock(true);});}catch{this.active=true;this.onLock(true);}}
 /** Release input capture for a DOM dialog. */
 unlock(){this.active=false;this.clear();if(document.pointerLockElement)document.exitPointerLock();}
 /** Clear held inputs to prevent movement after focus loss. */
 clear(){this.keys.clear();this.pressed.clear();this.left=this.right=this.pick=this.tapBreak=false;this.moveX=this.moveZ=0;}
 /** True while a key is down. */
 down(code){return this.keys.has(code);}
 /** Consume a single key edge, independent of render cadence. */
 consume(code){const value=this.pressed.has(code);this.pressed.delete(code);return value;}
}
