/** Small, throttled DOM updates; gameplay rendering stays in WebGL. */
export class HUD{
 /** Cache frequently updated nodes. */
 constructor(){this.debug=false;this.toastTimer=0;this.lastUpdate=0;this.fps=60;this.frames=0;this.fpsTime=0;this.mined=0;this.placed=0;this.crafted=0;this.biomes=new Set();this.tipDismissed=false;this.nodes=Object.fromEntries(['health-bar','hunger-bar','breath-bar','biome-name','time-label','coordinate-status','mode-status','survival-bars','debug','underwater','target-label','mining-progress'].map(id=>[id,document.getElementById(id)]));document.getElementById('journey-dismiss').onclick=()=>{this.tipDismissed=true;document.getElementById('journey-card').hidden=true;};}
 /** Restore exploration milestones. */
 restore(progress={}){this.mined=progress.mined||0;this.placed=progress.placed||0;this.crafted=progress.crafted||0;this.biomes=new Set(progress.biomes||[]);}
 /** Show a brief nonblocking in-world notice. */
 toast(message){const element=document.getElementById('toast');element.textContent=message;element.classList.add('visible');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>element.classList.remove('visible'),3300);}
 /** Discrete mining progress and target name. */
 target(hit,progress){this.nodes['target-label'].hidden=!hit;this.nodes['target-label'].textContent=hit?.name||'';const bar=this.nodes['mining-progress'];bar.hidden=progress<=0;bar.firstElementChild.style.width=`${Math.min(100,progress*100)}%`;}
 /** Generate ten pips for a twenty-point survival meter. */
 pips(value,icon){return Array.from({length:10},(_,i)=>`<svg class="icon${i*2>=value?' empty':''}"><use href="#i-${icon}"/></svg>`).join('');}
 /** Update interface at 4 Hz and collect real frame-rate measurements. */
 update(dt,engine){this.frames++;this.fpsTime+=dt;if(this.fpsTime>=.5){this.fps=Math.round(this.frames/this.fpsTime);this.frames=0;this.fpsTime=0;}this.lastUpdate+=dt;if(this.lastUpdate<.25)return;this.lastUpdate=0;const{player,world,renderer,sky,started}=engine,biome=world.biomeAt(player.position.x,player.position.z);this.nodes['biome-name'].textContent=biome;this.nodes['time-label'].textContent=sky.label();this.nodes['mode-status'].textContent=player.creative?'CREATIVE':'SURVIVAL';if(started){this.biomes.add(biome);this.nodes['coordinate-status'].textContent=`${Math.floor(player.position.x)} / ${Math.floor(player.position.y)} / ${Math.floor(player.position.z)}`;}this.nodes['health-bar'].innerHTML=this.pips(player.health,'heart');this.nodes['hunger-bar'].innerHTML=this.pips(player.hunger,'food');this.nodes['health-bar'].setAttribute('aria-label',`Health ${Math.ceil(player.health)} of 20`);this.nodes['hunger-bar'].setAttribute('aria-label',`Hunger ${Math.ceil(player.hunger)} of 20`);this.nodes['survival-bars'].hidden=player.creative;this.nodes['breath-bar'].hidden=!player.underwater;if(player.underwater)this.nodes['breath-bar'].innerHTML=Array.from({length:Math.ceil(player.breath)},()=>'<svg class="icon"><use href="#i-drop"/></svg>').join('');this.nodes.underwater.style.opacity=player.underwater&&started?'1':'0';
 this.nodes.debug.hidden=!this.debug;if(this.debug){let count=0;for(const c of world.chunks.values())count+=c.count;this.nodes.debug.textContent=`WILDWOOD / ENGINE\n${this.fps} FPS · ${renderer.gl.info.render.calls} draw calls\nXYZ ${player.position.toArray().map(n=>n.toFixed(2)).join(' / ')}\nChunk ${Math.floor(player.position.x/16)}, ${Math.floor(player.position.z/16)} · ${biome}\n${world.chunks.size} chunks · ${count.toLocaleString()} blocks\nQueue ${world.queue.length} · Workers ${world.workers.filter(w=>w.busy).length}/${world.workers.length}\nGPU geometries ${renderer.gl.info.memory.geometries}\nSeed ${world.seed} · ${player.creative?'Creative':'Survival'}`;}
 const journey=document.getElementById('journey-card');journey.hidden=!started||this.tipDismissed||engine.menus.opened;const stages=[['Get to know the woods','Hold left click to gather your first oak log.'],['A little room to create','Press E and turn a log into oak planks.'],['Leave your first mark','Right click to place a block. A home starts small.'],['Follow your curiosity','Find a new biome, or dig down in search of coal.']];const step=this.mined<1?0:this.crafted<1?1:this.placed<1?2:3;document.getElementById('journey-title').textContent=stages[step][0];document.getElementById('journey-detail').textContent=stages[step][1];document.querySelectorAll('.journey-dots i').forEach((e,i)=>e.classList.toggle('current',i<=step));}
 /** Flash damage without introducing a layout change. */
 damage(){const flash=document.getElementById('damage-flash');flash.style.opacity='1';setTimeout(()=>flash.style.opacity='0',180);}
 /** Serialize small objective counters alongside the world. */
 serialize(){return{mined:this.mined,placed:this.placed,crafted:this.crafted,biomes:[...this.biomes]};}
}
