const GUIDES={
 begin:`<div class="guide-step"><span class="step-number">01</span><div><h3>Make yourself at home.</h3><p>Use WASD to wander and Space to jump. Hold Shift to sprint. Point at an oak tree and hold left click to gather wood. Your starter satchel has a few supplies for the road.</p></div></div><div class="guide-step"><span class="step-number">02</span><div><h3>A log becomes a possibility.</h3><p>Press E to open your satchel. Craft logs into planks, then make a workbench. Keep it in your bag or place it nearby to unlock glass, bricks, and tools. A stone pickaxe makes mining much quicker.</p></div></div><div class="guide-step"><span class="step-number">03</span><div><h3>Go a little further.</h3><p>Scroll or press 1–9 to choose a block, then right click to build. Gather wild berries from oak leaves and right click to eat them. Bring torches into caves, and leave a trail home.</p></div></div>`,
 controls:`<div class="controls-grid">${[['W A S D','Walk'],['SPACE','Jump / swim up'],['SHIFT','Sprint'],['CTRL','Crouch / fly down'],['MOUSE','Look around'],['LEFT CLICK','Hold to mine'],['RIGHT CLICK','Place / eat'],['MIDDLE CLICK','Pick block'],['1–9 / SCROLL','Select slot'],['E','Open satchel'],['Q','Drop one item'],['F','Fly in creative'],['F3','Engine details'],['ESC','Pause & settings']].map(([key,label])=>`<div class="control-row"><span>${label}</span><kbd>${key}</kbd></div>`).join('')}</div><div class="guide-step"><span class="step-number">↗</span><div><h3>A lighter touch.</h3><p>On a touch screen, use the left stick to move and drag on the world to look. Tap to mine, hold to place, and use the arrow button to jump. Tap the grid to open your satchel.</p></div></div>`,
 world:`<div class="guide-biomes">${[['Oak forest','A good place to begin. Logs for building, leaves for berries, and shade for a quiet afternoon.'],['Meadow & riverbank','Open hills meet winding water. Find sand along the shore, and remember to come up for air.'],['Desert & highlands','Keep walking. Warm, dry sands and stony mountain ridges appear as the climate changes.'],['Under the surface','Coal hides near the surface; iron runs deeper. Torches light the way. Bedrock marks the bottom.']].map(([name,text])=>`<div class="biome-guide"><h3>${name}</h3><p>${text}</p></div>`).join('')}</div><div class="guide-step"><span class="step-number">∞</span><div><h3>Your world keeps going.</h3><p>Every seed grows an endless, repeatable landscape. A day lasts ten minutes. Your changes save as you go; unvisited wilderness stays wild. Switch to creative in settings for unlimited building and flight.</p></div></div>`
};
/** Dialog lifecycle, settings binding, and keyboard focus containment. */
export class Menus{
 /** @param {import('../core/Engine.js').Engine} engine */
 constructor(engine){this.engine=engine;this.opened=null;this.lastFocus=null;this.layer=document.getElementById('modal-layer');this.returnTo=null;const bind=(id,fn)=>document.getElementById(id).onclick=fn;
 bind('settings-button',()=>this.show('pause'));bind('help-button',()=>this.show('guide'));bind('nav-guide',()=>this.show('guide'));bind('pause-guide',()=>this.show('guide'));bind('nav-play',()=>this.engine.started?this.close(true):this.close(false));document.querySelector('.brand').onclick=e=>{e.preventDefault();if(engine.started)this.show('pause');};bind('inventory-button',()=>this.show('inventory'));bind('resume-button',()=>this.close(true));bind('return-home',()=>{engine.save();this.close(false);engine.home();});bind('creative-toggle',()=>{engine.setCreative(!engine.player.creative);this.updateMode();});bind('respawn-button',()=>engine.respawn());document.querySelectorAll('.close-modal').forEach(button=>button.onclick=()=>this.close(engine.started));this.layer.addEventListener('click',e=>{if(e.target===this.layer&&this.opened!=='death')this.close(engine.started);});
 for(const key of['sensitivity','distance','fov']){const input=document.getElementById(key);input.value=engine.settings[key];const update=()=>{engine.settings[key]=Number(input.value);engine.settings.save();document.getElementById(`${key}-value`).textContent=key==='sensitivity'?`${Math.round(input.value*100)}%`:key==='distance'?`${input.value} chunks`:`${input.value}°`;};input.oninput=update;update();}
 document.querySelectorAll('[data-guide]').forEach(button=>button.onclick=()=>this.guide(button.dataset.guide));this.guide('begin');
 document.addEventListener('keydown',e=>{if(!this.opened||e.code!=='Tab')return;const modal=document.getElementById(`${this.opened}-modal`),elements=[...modal.querySelectorAll('button:not(:disabled),input')].filter(el=>el.offsetParent!==null);if(!elements.length)return;const first=elements[0],last=elements[elements.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});}
 /** Pause and display a single dialog, releasing pointer lock. */
 show(name){this.lastFocus=document.activeElement;this.opened=name;this.engine.input.unlock();this.engine.accumulator=0;if(this.engine.started)this.engine.save();this.layer.hidden=false;for(const modal of this.layer.children)modal.hidden=modal.id!==`${name}-modal`;document.getElementById(`${name}-modal`).setAttribute('role','dialog');document.getElementById(`${name}-modal`).setAttribute('aria-modal','true');document.getElementById('crosshair').hidden=true;this.engine.renderer.highlight.visible=false;this.engine.renderer.crack.visible=false;this.engine.hud.target(null,0);this.engine.inventory.held=null;this.engine.inventory.render();this.updateMode();const focus=document.getElementById(`${name}-modal`).querySelector('button');focus?.focus();}
 /** Close the dialog and optionally resume pointer capture. */
 close(resume=false){if(this.opened==='death')return;this.opened=null;this.layer.hidden=true;this.lastFocus?.focus?.();if(resume&&this.engine.started){this.engine.input.lock();document.getElementById('crosshair').hidden=false;}}
 /** Synchronize creative mode copy. */
 updateMode(){document.getElementById('creative-toggle').textContent=this.engine.player.creative?'Switch to survival mode':'Switch to creative mode';}
 /** Change guide chapters without leaving the dialog. */
 guide(tab){document.getElementById('guide-content').innerHTML=GUIDES[tab]||GUIDES.begin;document.querySelectorAll('[data-guide]').forEach(button=>{const selected=button.dataset.guide===tab;button.classList.toggle('active',selected);button.setAttribute('aria-selected',String(selected));});}
}
